### ISSUE TITLE
White space when scrolling page on Android 9

### ISSUE THREAD

**Issue by osmers** [digitalfabrik/integreat-app#2456] opened 2023-09-20 09:45 UTC
### Describe the Bug

Open this page https://integreat.app/kreisolpe/de/ukraine/faqs-einreise-aus-der-ukraine-und-aufenthalt-in-deutschland on Android 9 - when scrolling the largest part of the text will be covered by a white space and the text only scrolls at the bottom edge (see video).

According to the user, this only happens on this single page. Therefore it might also be connected to the html on the page.

### Expected Behavior

Page shows all the information and scrolls through it.

### Actual Behavior

After starting to scroll the text gets covered by a white space. 

### Additional Information

Video: 

https://github.com/digitalfabrik/integreat-app/assets/64901227/71795fd8-c7a0-495b-9e9a-875ac688c6fa

Seems to happen only on Android 9 - tested on 12 and 13, works fine.

**Comment by LeandraH** [comment] 2023-09-20 10:51
Can't reproduce it on an emulated Pixel 2 with Android 9 :(

**Comment by sarahsporck** [comment] 2023-10-05 13:42
Can also not reproduce. Maybe close this then?

**Closed** 2023-10-06 09:02 UTC
Labels: ready, Native, reproduction-needed, Android
