### ISSUE TITLE
Add translation for "Link kopieren"

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/integreat-app#2481] opened 2023-09-27 07:30 UTC
### Describe the Bug

The toolar-button "Link kopieren" does not have a translation.

### Steps to Reproduce

1. Go to https://integreat.app/neuss/tr
2. Look at the toolbar

### Expected Behavior

Translation should be there

### Actual Behavior

German everywhere

**Comment by ztefanie** [comment] 2023-09-27 08:07
Duplicate of [#2245 ](https://github.com/digitalfabrik/integreat-app/issues/2445)

**Closed by ztefanie** 2023-09-27 08:07 UTC
Labels: bug
