### ISSUE TITLE
unknown error at Testumgebung

### ISSUE THREAD

**Issue by Docmale** [digitalfabrik/integreat-app#2474] opened 2023-09-25 09:00 UTC
### Describe the Bug
Only in location "Testumgebung" selecting Imprint results in unknown error. (Only Malte app)

### Steps to Reproduce

1. select Testumgebung 
2. Click on Imprint
3. See error

**Comment by LeandraH** [comment] 2023-09-25 10:40
Sadly not a duplicate of https://github.com/digitalfabrik/integreat-app/issues/2462

**Comment by steffenkleinle** [comment] 2023-09-30 09:57
This error just happened because there was no disclaimer set in the cms. Closing.

**Closed** 2023-10-02 07:49 UTC
Labels: bug, Native, Malte
