### ISSUE TITLE
Pushnews not pushed in Android devices

### ISSUE THREAD

**Issue by vthejay** [digitalfabrik/integreat-app#2438] opened 2023-09-12 06:58 UTC
### Describe the Bug

The pushnews are not pushed in android devices.
### Steps to Reproduce

1. Go to '...'Testumgebung
2. Click on '....'Nachrichten. Send the news.
3. Check your mobile device (Android)
4. No push news seen.

### Expected Behavior

The pushnews is pushed to the device, when a push news is sent.
### Actual Behavior

Nothing happens. The news is shown under the "News" page though if you navigate to the "News" section.
### Additional Information

It does not matter if the app is running in the background or if the app is completely killed. Nothing happens.
Tested on Android 13 with the App Version 2023.9.1.
on IoS it works well.
<details>
  <summary>Traceback</summary>

```

```

</details>

**Comment by SteffiStuffel** [comment] 2023-09-13 07:47
@vthejay Are you sure PN are not disabled, neither in the app nor in the system settings (settings -> apps -> Integreat -> permissions)?

Cannot reproduce.

**Comment by vthejay** [comment] 2023-09-13 08:11
Very sure. Tested it together with Sarah on her phone. May be @sarahsporck can give more details?

**Comment by FritjofK** [comment] 2023-09-13 08:16
I recieved quite a few from Testumgebung on Android 12 with Integrat 2023.7.5. 
I updated now to 2023.9.1 and will keep an eye on the behavior.

**Comment by vthejay** [comment] 2023-09-13 13:12
Importatnt:
We have atleast 5 Municipalities reporting the same problem in the past week. So, it is not a problem only for one person.

**Comment by steffenkleinle** [comment] 2023-09-14 09:37
Possible duplicate of https://github.com/digitalfabrik/integreat-app/issues/2298

**Comment by vthejay** [comment] 2023-09-18 12:32
Probably only in Android 13?
Could someone who has Android 13 please test this?

**Comment by steffenkleinle** [comment] 2023-09-18 12:52
@vthejay do you never get PNs or just sometimes? In the linked issue (#2298) one user (2.) apparently gets them "unregelmäßig" with One UI 5.1 (i.e. android 13).

**Comment by vthejay** [comment] 2023-09-18 12:55
@steffenkleinle I have LineageOS without microg. So, I never get PNs. Because of municipalities reporting this quite often last week, I did test it last week together with @sarahsporck . She did not get the PN. She had Android 13 as well.

**Comment by SteffiStuffel** [comment] 2023-09-19 06:08
I have Android 13 and get PN correctly

**Closed** 2023-09-30 10:41 UTC
Labels: bug, Native, android, prio:high
