### ISSUE TITLE
Handle failed unsubscriptions from notifications

### ISSUE THREAD

**Issue by LeandraH** [digitalfabrik/integreat-app#2708] opened 2024-03-02 10:04 UTC
**Is your feature request related to a problem? Please describe.**
When a user switches language or city, they are currently ideally subscribed to notifications from the new language/city combination and unsubscribed from the old one. But if the unsubscription fails, the user receives notifications from both the old and the new combination.

**Describe the solution you'd like**
We should handle it when unsubscribing fails. Maybe show an error to the user with a button to re-try? Or automatically re-try up to three times in the background?

**For testing**
Sorry, I'm not sure how well this can be tested because it would need the language/city change to work but the notification unsubscription to fail.

**Comment by steffenkleinle** [comment] 2024-03-02 14:57
Possibly a duplicate of #2142 depending on how we want to implement this.

**Comment by f1sh1918** [comment] 2024-03-20 10:09
i think we should wait for the cms endpoint which is a more durable implementation. will be closed instead of #2142

**Closed by f1sh1918** 2024-03-20 10:09 UTC
Labels: Native
